name: aqualink
description: Smart Irrigation Dashboard for University of the Western Cape
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # Charts
  fl_chart: ^0.66.0
  
  # Icons
  lucide_icons_flutter: ^1.0.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # HTTP
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
